title: anietie etuk
logo: assets/pic 2.jpg
theme: jekyll-theme-minimal

# Contact Information
location: Port Harcourt, Rivers State, Nigeria
website: https://etukanietie.com
twitter: @etukanietie
email: etukanietie@yahoo.com
