title: anietie etuk
logo: assets/pic 2.jpg
theme: jekyll-theme-minimal

# Contact Information
location: New York, New York
website: https://aboutmonica.com
twitter: @indigitalcolor
email: indigitalcolor@hachyderm.io
