title: Anietie Etuk
logo: assets/pic 2.jpg

location: Port Harcourt, Rivers State, Nigeria
website: https://etukanietie.com
twitter: @etukanietie
email: etukanietie@yahoo.com


theme: jekyll-theme-minimal
plugins:
  - jekyll-feed




